baseURL: "https://cgnkskn.github.io/" 
title: Cagin 
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Work in Progress
          url: papers/
        - name: Curriculum Vitae
          url: cagin_cv.pdf

params:
    description: "I am a Ph.D. candidate at CERGE-EI (Center for Economic Research and Graduate Education—Economics Institute), a joint workplace of Charles University and the Czech Academy of Sciences. "
    author: Cagin Keskin
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Work in Progress", "Curriculum Vitae"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Cagin Keskin
          subtitle: "I am a Ph.D. candidate at CERGE-EI (Center for Economic Research and Graduate Education—Economics Institute), a joint workplace of Charles University and the Czech Academy of Sciences.
          <br><br> My research interest lies in endogenous growth theory, firm dynamics, and intangible assets. <br><br> You can reach out to me at <b> Cagin.Keskin@cerge-ei.cz <b> "
          imageUrl: "cagin.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Cagin Keskin
          buttons:
            - name: Work in Progress
              url: papers/
            - name: Curriculum Vitae
              url: cagin_cv.pdf
    socialIcons:
        - name: Email
          url: mailto:Cagin.Keskin@cerge-ei.cz
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/cgnkskn
        - name: Twitter
          url: https://twitter.com/cgnkskn

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Cagin Keskin"
      icon: atom.ico
      iconHeight: 18
      
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2